apiVersion: v1
kind: Secret
metadata:
  name: {{ include "morning-bot.fullname" . }}-secrets
  labels:
    {{- include "morning-bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  GEMINI_API_KEY: {{ .Values.secrets.geminiApiKey | quote }}
  FB_PAGE_ID: {{ .Values.secrets.fbPageId | quote }}
  FB_PAGE_ACCESS_TOKEN: {{ .Values.secrets.fbPageAccessToken | quote }}
